name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: MatthewGrasberger.tex
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          # Artifact name
          name: MatthewGrasberger.pdf
          path: MatthewGrasberger.pdf
      - name: Send mail to check PDF compilation before upload to grasbergerm.com
        uses: dawidd6/action-send-mail@v3
        with:
          
          # Required mail server address:
          server_address: smtp.office365.com
          # Required mail server port:
          server_port: 588
          secure: true
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: grasbergerm@gmail.com
          # Required sender full name (address can be skipped):
          from: Github Actions # <user@example.com>
          # Optional plain body:
          body: Resume compilation result from ${{github.repository}}. See attachment.
          attachments: MatthewGrasberger.pdf
  upload_files:
    runs-on: ubuntu-latest
    environment: 'grasbergerm.com'
    needs: build_latex
    name: Uploads resume PDF to grasbergerm.com
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: MatthewGrasberger.pdf
    - name: SFTP
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
      uses: Creepios/sftp-action@v1.0.3
      with:
        host: ${{ env.HOST }}
        port: 22
        username: ${{ env.USERNAME }}
        password: ${{ env.PASSWORD }}
        localPath: 'MatthewGrasberger.pdf'
        remotePath: ${{ env.REMOTE_PATH }}
