name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: MatthewGrasberger.tex
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          # Artifact name
          name: MatthewGrasberger.pdf
          path: MatthewGrasberger.pdf
  upload_files:
    runs-on: ubuntu-latest
    environment: 'grasbergerm.com'
    needs: build_latex
    name: Uploads resume PDF to grasbergerm.com
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: MatthewGrasberger.pdf
    - name: SFTP
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
      uses: Creepios/sftp-action@v1.0.3
      with:
        host: ${{ env.HOST }}
        port: 22
        username: ${{ env.USERNAME }}
        password: ${{ env.PASSWORD }}
        localPath: 'MatthewGrasberger.pdf'
        remotePath: ${{ env.REMOTE_PATH }}
